import type { User, KYC, Wallet, Transaction, Car, Auction, Bid, Notification } from "./types"

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: "user-1",
    email: "admin@lelangmobil.com",
    phone: "081234567890",
    name: "Admin LelangMobil",
    role: "ADMIN",
    emailVerified: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-01-01"),
  },
  {
    id: "user-2",
    email: "budi@gmail.com",
    phone: "081234567891",
    name: "Budi Santoso",
    role: "USER",
    emailVerified: true,
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-06-15"),
  },
  {
    id: "user-3",
    email: "siti@gmail.com",
    phone: "081234567892",
    name: "Siti Rahayu",
    role: "USER",
    emailVerified: false,
    createdAt: new Date("2024-07-20"),
    updatedAt: new Date("2024-07-20"),
  },
  {
    id: "user-4",
    email: "ahmad@gmail.com",
    phone: "081234567893",
    name: "Ahmad Wijaya",
    role: "USER",
    emailVerified: false,
    createdAt: new Date("2024-08-10"),
    updatedAt: new Date("2024-08-10"),
  },
]

// Dummy KYC
export const dummyKYC: KYC[] = [
  {
    id: "kyc-1",
    userId: "user-2",
    ktpNumber: "3171234567890001",
    ktpImageUrl: "/ktp-indonesia-identity-card.jpg",
    selfieImageUrl: "/indonesian-man-selfie-holding-id.jpg",
    status: "APPROVED",
    approvedAt: new Date("2024-06-16"),
    approvedBy: "user-1",
    createdAt: new Date("2024-06-15"),
    updatedAt: new Date("2024-06-16"),
  },
  {
    id: "kyc-2",
    userId: "user-3",
    ktpNumber: "3171234567890002",
    ktpImageUrl: "/ktp-indonesia-identity-card-woman.jpg",
    selfieImageUrl: "/indonesian-woman-selfie-holding-id.jpg",
    status: "PENDING",
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date("2024-11-25"),
  },
  {
    id: "kyc-3",
    userId: "user-4",
    ktpNumber: "3171234567890003",
    ktpImageUrl: "/ktp-indonesia-identity-card.jpg",
    selfieImageUrl: "/indonesian-man-selfie-holding-id-card.jpg",
    status: "PENDING",
    createdAt: new Date("2024-11-26"),
    updatedAt: new Date("2024-11-26"),
  },
]

// Dummy Wallets
export const dummyWallets: Wallet[] = [
  {
    id: "wallet-1",
    userId: "user-2",
    balance: 25000000,
    holdBalance: 5000000,
    createdAt: new Date("2024-06-16"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "wallet-2",
    userId: "user-3",
    balance: 0,
    holdBalance: 0,
    createdAt: new Date("2024-07-20"),
    updatedAt: new Date("2024-07-20"),
  },
  {
    id: "wallet-3",
    userId: "user-4",
    balance: 0,
    holdBalance: 0,
    createdAt: new Date("2024-08-10"),
    updatedAt: new Date("2024-08-10"),
  },
]

// Dummy Transactions
export const dummyTransactions: Transaction[] = [
  {
    id: "trx-1",
    userId: "user-2",
    walletId: "wallet-1",
    type: "BONUS",
    amount: 1000000,
    status: "COMPLETED",
    notes: "Bonus KYC Approved",
    processedAt: new Date("2024-06-16"),
    processedBy: "user-1",
    createdAt: new Date("2024-06-16"),
    updatedAt: new Date("2024-06-16"),
  },
  {
    id: "trx-2",
    userId: "user-2",
    walletId: "wallet-1",
    type: "DEPOSIT",
    amount: 20000000,
    status: "COMPLETED",
    bankName: "BCA",
    proofImageUrl: "/bank-transfer-receipt-bca.jpg",
    processedAt: new Date("2024-06-17"),
    processedBy: "user-1",
    createdAt: new Date("2024-06-17"),
    updatedAt: new Date("2024-06-17"),
  },
  {
    id: "trx-3",
    userId: "user-2",
    walletId: "wallet-1",
    type: "DEPOSIT",
    amount: 10000000,
    status: "PENDING",
    bankName: "MANDIRI",
    proofImageUrl: "/bank-transfer-receipt-mandiri.jpg",
    createdAt: new Date("2024-11-26"),
    updatedAt: new Date("2024-11-26"),
  },
  {
    id: "trx-4",
    userId: "user-3",
    walletId: "wallet-2",
    type: "DEPOSIT",
    amount: 15000000,
    status: "PENDING",
    bankName: "BRI",
    proofImageUrl: "/bank-transfer-receipt-bri.jpg",
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date("2024-11-25"),
  },
]

// Dummy Cars
export const dummyCars: Car[] = [
  {
    id: "car-1",
    brand: "Toyota",
    model: "Avanza G",
    year: 2022,
    odometer: 25000,
    grade: "A",
    location: "Jakarta Selatan",
    transmission: "AT",
    fuel: "BENSIN",
    taxStatus: "Hidup",
    taxExpiry: new Date("2025-03-15"),
    color: "Putih",
    engineCapacity: "1500cc",
    description:
      "Kondisi sangat terawat, servis rutin di bengkel resmi Toyota. Interior bersih, tidak ada lecet atau baret. Mobil keluarga, jarang dipakai keluar kota.",
    images: [
      "/white-toyota-avanza-2022-front-view-showroom.jpg",
      "/toyota-avanza-interior-dashboard-clean.jpg",
      "/toyota-avanza-side-view-white-car.jpg",
      "/toyota-avanza-rear-view-parking-lot.jpg",
    ],
    createdAt: new Date("2024-11-20"),
    updatedAt: new Date("2024-11-20"),
  },
  {
    id: "car-2",
    brand: "Mitsubishi",
    model: "Pajero Sport Dakar",
    year: 2021,
    odometer: 45000,
    grade: "A",
    location: "Surabaya",
    transmission: "AT",
    fuel: "DIESEL",
    taxStatus: "Hidup",
    taxExpiry: new Date("2025-05-20"),
    color: "Hitam",
    engineCapacity: "2400cc",
    description:
      "Pajero Sport Dakar Ultimate 4x4. Kondisi istimewa, baru ganti ban Bridgestone. Fitur lengkap termasuk sunroof, leather seat, dan 360 camera.",
    images: [
      "/black-mitsubishi-pajero-sport-2021-front-view-luxu.jpg",
      "/pajero-sport-interior-leather-seats-premium.jpg",
      "/mitsubishi-pajero-sport-side-view-black-suv.jpg",
      "/black-mitsubishi-pajero-sport-2021-front-view-luxu.jpg",
    ],
    createdAt: new Date("2024-11-18"),
    updatedAt: new Date("2024-11-18"),
  },
  {
    id: "car-3",
    brand: "Toyota",
    model: "Fortuner VRZ",
    year: 2023,
    odometer: 12000,
    grade: "A",
    location: "Bandung",
    transmission: "AT",
    fuel: "DIESEL",
    taxStatus: "Hidup",
    taxExpiry: new Date("2025-08-10"),
    color: "Silver",
    engineCapacity: "2400cc",
    description:
      "Fortuner VRZ TRD terbaru. Masih dalam masa garansi resmi Toyota. Mobil seperti baru, pemakaian sangat rendah. Cocok untuk keluarga yang suka traveling.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    createdAt: new Date("2024-11-15"),
    updatedAt: new Date("2024-11-15"),
  },
  {
    id: "car-4",
    brand: "Honda",
    model: "Brio RS",
    year: 2023,
    odometer: 8000,
    grade: "A",
    location: "Jakarta Barat",
    transmission: "AT",
    fuel: "BENSIN",
    taxStatus: "Hidup",
    taxExpiry: new Date("2025-09-05"),
    color: "Merah",
    engineCapacity: "1200cc",
    description:
      "Honda Brio RS CVT. Mobil sporty dan irit BBM. Kondisi like new, cocok untuk anak muda atau first car. Fitur safety lengkap.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    createdAt: new Date("2024-11-22"),
    updatedAt: new Date("2024-11-22"),
  },
  {
    id: "car-5",
    brand: "Toyota",
    model: "Innova Reborn V",
    year: 2020,
    odometer: 65000,
    grade: "B",
    location: "Medan",
    transmission: "AT",
    fuel: "DIESEL",
    taxStatus: "Hidup",
    taxExpiry: new Date("2025-02-28"),
    color: "Abu-abu",
    engineCapacity: "2400cc",
    description:
      "Innova Reborn V Diesel. Mobil favorit keluarga Indonesia. Ada beberapa lecet kecil di body, tapi mesin sangat sehat. Servis rutin di bengkel resmi.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    createdAt: new Date("2024-11-10"),
    updatedAt: new Date("2024-11-10"),
  },
  {
    id: "car-6",
    brand: "Suzuki",
    model: "Ertiga GX",
    year: 2022,
    odometer: 30000,
    grade: "B",
    location: "Semarang",
    transmission: "MT",
    fuel: "BENSIN",
    taxStatus: "Hidup",
    taxExpiry: new Date("2025-04-12"),
    color: "Putih",
    engineCapacity: "1500cc",
    description:
      "Suzuki Ertiga GX manual. Mobil keluarga yang irit dan nyaman. Interior masih bagus, eksterior ada beberapa baret ringan. Cocok untuk budget terbatas.",
    images: [
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
      "/placeholder.svg?height=600&width=800",
    ],
    createdAt: new Date("2024-11-12"),
    updatedAt: new Date("2024-11-12"),
  },
]

// Dummy Auctions
export const dummyAuctions: Auction[] = [
  {
    id: "auction-1",
    carId: "car-1",
    car: dummyCars[0],
    startingPrice: 180000000,
    currentPrice: 195000000,
    minimumIncrement: 500000,
    startTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // Started 2 hours ago
    endTime: new Date(Date.now() + 4 * 60 * 60 * 1000), // Ends in 4 hours
    status: "LIVE",
    totalBids: 12,
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date(),
  },
  {
    id: "auction-2",
    carId: "car-2",
    car: dummyCars[1],
    startingPrice: 450000000,
    currentPrice: 478000000,
    minimumIncrement: 1000000,
    startTime: new Date(Date.now() - 1 * 60 * 60 * 1000), // Started 1 hour ago
    endTime: new Date(Date.now() + 5 * 60 * 60 * 1000), // Ends in 5 hours
    status: "LIVE",
    totalBids: 8,
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date(),
  },
  {
    id: "auction-3",
    carId: "car-3",
    car: dummyCars[2],
    startingPrice: 520000000,
    currentPrice: 520000000,
    minimumIncrement: 1000000,
    startTime: new Date(Date.now() + 2 * 60 * 60 * 1000), // Starts in 2 hours
    endTime: new Date(Date.now() + 8 * 60 * 60 * 1000), // Ends in 8 hours
    status: "UPCOMING",
    totalBids: 0,
    createdAt: new Date("2024-11-26"),
    updatedAt: new Date(),
  },
  {
    id: "auction-4",
    carId: "car-4",
    car: dummyCars[3],
    startingPrice: 165000000,
    currentPrice: 182000000,
    minimumIncrement: 500000,
    startTime: new Date(Date.now() - 3 * 60 * 60 * 1000), // Started 3 hours ago
    endTime: new Date(Date.now() + 1 * 60 * 60 * 1000), // Ends in 1 hour
    status: "LIVE",
    totalBids: 15,
    createdAt: new Date("2024-11-25"),
    updatedAt: new Date(),
  },
  {
    id: "auction-5",
    carId: "car-5",
    car: dummyCars[4],
    startingPrice: 280000000,
    currentPrice: 295000000,
    minimumIncrement: 500000,
    startTime: new Date(Date.now() - 24 * 60 * 60 * 1000), // Started yesterday
    endTime: new Date(Date.now() - 2 * 60 * 60 * 1000), // Ended 2 hours ago
    status: "ENDED",
    winnerId: "user-2",
    winner: dummyUsers[1],
    totalBids: 22,
    createdAt: new Date("2024-11-24"),
    updatedAt: new Date(),
  },
]

// Dummy Bids
export const dummyBids: Bid[] = [
  {
    id: "bid-1",
    auctionId: "auction-1",
    userId: "user-2",
    user: dummyUsers[1],
    amount: 195000000,
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "bid-2",
    auctionId: "auction-1",
    userId: "user-3",
    user: dummyUsers[2],
    amount: 192000000,
    status: "OUTBID",
    createdAt: new Date(Date.now() - 45 * 60 * 1000),
  },
  {
    id: "bid-3",
    auctionId: "auction-2",
    userId: "user-2",
    user: dummyUsers[1],
    amount: 478000000,
    status: "ACTIVE",
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
  },
]

// Real Notifications (Dynamic based on user actions)
export const dummyNotifications: Notification[] = [
  {
    id: "notif-1",
    userId: "user-2",
    type: "KYC_APPROVED",
    title: "KYC Disetujui",
    message: "Selamat! Verifikasi KYC Anda telah disetujui oleh admin. Bonus Rp 1.000.000 telah ditambahkan ke wallet Anda. Sekarang Anda dapat mengikuti lelang.",
    isRead: true,
    createdAt: new Date("2024-06-16T10:30:00"),
  },
  {
    id: "notif-2",
    userId: "user-2",
    type: "DEPOSIT_APPROVED",
    title: "Deposit Berhasil Dikonfirmasi",
    message: "Deposit sebesar Rp 20.000.000 via BCA telah dikonfirmasi oleh admin dan ditambahkan ke saldo Anda. Saldo tersedia: Rp 21.000.000",
    isRead: true,
    createdAt: new Date("2024-06-17T14:20:00"),
  },
  {
    id: "notif-3",
    userId: "user-2",
    type: "OUTBID",
    title: "Bid Anda Terkalahkan!",
    message: "Pengguna lain mengajukan bid Rp 195.500.000 untuk Toyota Avanza G 2022. Bid Anda (Rp 195.000.000) tidak lagi tertinggi. Segera pasang bid baru sebelum lelang berakhir!",
    isRead: false,
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "notif-4",
    userId: "user-2",
    type: "AUCTION_WON",
    title: "Selamat! Anda Memenangkan Lelang",
    message: "Anda memenangkan lelang Toyota Innova Reborn V 2020 dengan bid tertinggi Rp 295.000.000! Silakan selesaikan pembayaran dalam 3x24 jam. Tim kami akan menghubungi Anda untuk proses serah terima.",
    isRead: false,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "notif-5",
    userId: "user-2",
    type: "AUCTION_STARTED",
    title: "Lelang Dimulai!",
    message: "Lelang Mitsubishi Pajero Sport Dakar 2021 yang Anda ikuti telah dimulai! Harga awal: Rp 450.000.000. Jangan lewatkan kesempatan ini!",
    isRead: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "notif-6",
    userId: "user-2",
    type: "WITHDRAW_COMPLETED",
    title: "Penarikan Selesai",
    message: "Penarikan dana sebesar Rp 5.000.000 ke rekening BCA atas nama Budi Santoso telah berhasil diproses. Dana akan masuk ke rekening Anda dalam 1x24 jam.",
    isRead: true,
    createdAt: new Date("2024-11-20T09:15:00"),
  },
  {
    id: "notif-7",
    userId: "user-2",
    type: "BONUS_RECEIVED",
    title: "Bonus Diterima!",
    message: "Anda mendapat bonus Rp 500.000 sebagai member setia LelangMobil! Bonus telah ditambahkan ke wallet Anda dan dapat langsung digunakan untuk bid.",
    isRead: false,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "notif-8",
    userId: "user-2",
    type: "DEPOSIT_APPROVED",
    title: "Deposit Dikonfirmasi",
    message: "Deposit Rp 10.000.000 via Mandiri telah dikonfirmasi. Total saldo Anda sekarang: Rp 25.000.000. Terima kasih telah menggunakan LelangMobil!",
    isRead: true,
    createdAt: new Date("2024-11-25T16:45:00"),
  },
]

// Testimonials - 20+ Real Indonesian testimonials
export const testimonials = [
  {
    id: 1,
    name: "Budi Santoso",
    profession: "Pengusaha",
    location: "Jakarta Selatan",
    car: "Toyota Innova Reborn V 2020",
    purchasePrice: "Rp 295.000.000",
    marketPrice: "Rp 320.000.000",
    savings: "Rp 25.000.000",
    message: "Alhamdulillah dapat Innova Reborn dengan harga 25 juta lebih murah dari pasaran! Prosesnya transparan, mobil sesuai deskripsi. Tim LelangMobil sangat profesional dalam penanganan dokumen dan BPKB. Highly recommended untuk yang cari mobil berkualitas dengan harga bersaing.",
    image: "/professional-man-indonesian.jpg",
    carImage: "/white-toyota-avanza-2022-front-view-showroom.jpg",
    rating: 5,
    date: "November 2024",
    verified: true
  },
  {
    id: 2,
    name: "Siti Rahayu",
    profession: "Ibu Rumah Tangga",
    location: "Bandung, Jawa Barat",
    car: "Honda Brio RS CVT 2023",
    purchasePrice: "Rp 182.000.000",
    marketPrice: "Rp 195.000.000",
    savings: "Rp 13.000.000",
    message: "Pertama kali ikut lelang online, awalnya ragu tapi ternyata sistemnya mudah dipahami. Customer service sabar banget jelasinnya step by step. Dapat Brio RS untuk anak yang baru lulus kuliah, kondisi like new dan harga jauh lebih murah. Terima kasih LelangMobil!",
    image: "/business-woman-indonesian.jpg",
    carImage: "/white-toyota-avanza-2022-front-view-showroom.jpg",
    rating: 5,
    date: "Oktober 2024",
    verified: true
  },
  {
    id: 3,
    name: "Ahmad Wijaya",
    profession: "Karyawan Swasta",
    location: "Surabaya, Jawa Timur",
    car: "Mitsubishi Pajero Sport Dakar 2021",
    purchasePrice: "Rp 478.000.000",
    marketPrice: "Rp 510.000.000",
    savings: "Rp 32.000.000",
    message: "Sudah 3 kali menang lelang di sini, selalu puas dengan hasilnya. Pajero Sport Dakar yang saya menangkan kondisinya excellent, semua fitur berfungsi normal. Proses serah terima di kantor cabang Surabaya juga lancar. Tim teknis mereka benar-benar ahli dalam pengecekan kondisi kendaraan.",
    image: "/tech-man-indonesian.jpg",
    carImage: "/black-mitsubishi-pajero-sport-2021-front-view-luxu.jpg",
    rating: 5,
    date: "September 2024",
    verified: true
  },
  {
    id: 4,
    name: "Dewi Anggraini",
    profession: "Dokter",
    location: "Medan, Sumatera Utara",
    car: "Toyota Avanza G 2022",
    purchasePrice: "Rp 195.000.000",
    marketPrice: "Rp 210.000.000",
    savings: "Rp 15.000.000",
    message: "Sebagai dokter yang sibuk, saya butuh proses yang efisien. LelangMobil memberikan solusi terbaik. Dari registrasi, KYC, deposit, sampai lelang semuanya bisa online. Avanza yang saya dapat untuk praktik keliling sangat sesuai kebutuhan. Withdraw saldo juga cepat, kurang dari 24 jam sudah masuk rekening BCA.",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/toyota-avanza-2022.svg",
    rating: 5,
    date: "Agustus 2024",
    verified: true
  },
  {
    id: 5,
    name: "Rizki Pratama",
    profession: "Content Creator",
    location: "Yogyakarta, DIY",
    car: "Honda Jazz RS CVT 2022",
    purchasePrice: "Rp 245.000.000",
    marketPrice: "Rp 265.000.000",
    savings: "Rp 20.000.000",
    message: "Sebagai content creator yang sering traveling, butuh mobil yang reliable dan stylish. Jazz RS yang saya menangkan perfect banget! Fitur Honda Sensing lengkap, interior masih wangi baru. Yang paling suka, proses lelangnya seru dan fair. Semua bid history transparan, jadi tau persaingannya gimana.",
    image: "/avatar-man-2.svg",
    carImage: "/cars/honda-crv-2023.svg",
    rating: 5,
    date: "Juli 2024",
    verified: true
  },
  {
    id: 6,
    name: "Indira Sari",
    profession: "Marketing Manager",
    location: "Makassar, Sulawesi Selatan",
    car: "Suzuki Ertiga GX 2022",
    purchasePrice: "Rp 185.000.000",
    marketPrice: "Rp 200.000.000",
    savings: "Rp 15.000.000",
    message: "Pertama kali dengar tentang lelang mobil online dari teman kantor. Skeptis awalnya, tapi setelah coba ternyata legit dan menguntungkan. Ertiga untuk keluarga besar kami sangat pas, 7 seater dengan kondisi prima. Customer service Makassar juga ramah dan informatif. Pasti akan rekomendasikan ke keluarga dan teman.",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/toyota-avanza-2022.svg",
    rating: 5,
    date: "Juni 2024",
    verified: true
  },
  {
    id: 7,
    name: "Andi Wijaya",
    profession: "Wiraswasta",
    location: "Semarang, Jawa Tengah",
    car: "Honda HR-V E CVT 2021",
    purchasePrice: "Rp 285.000.000",
    marketPrice: "Rp 310.000.000",
    savings: "Rp 25.000.000",
    message: "Proses lelang sangat fair dan transparan. Saya bisa lihat semua bid history secara real-time. HR-V yang saya menangkan kondisinya mulus banget, kilometer rendah, service record lengkap. Tim LelangMobil juga bantu proses balik nama dengan cepat. Recommended!",
    image: "/avatar-man-1.svg",
    carImage: "/cars/honda-crv-2023.svg",
    rating: 5,
    date: "Desember 2024",
    verified: true
  },
  {
    id: 8,
    name: "Ratna Dewi",
    profession: "Guru",
    location: "Solo, Jawa Tengah",
    car: "Daihatsu Xenia R 2020",
    purchasePrice: "Rp 145.000.000",
    marketPrice: "Rp 160.000.000",
    savings: "Rp 15.000.000",
    message: "Sebagai guru dengan budget terbatas, LelangMobil sangat membantu. Dapat Xenia dengan harga jauh di bawah pasaran. Prosesnya mudah, customer service sabar jelasin step by step. Mobil sudah saya pakai 6 bulan, tidak ada masalah sama sekali. Terima kasih!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/toyota-avanza-2022.svg",
    rating: 5,
    date: "Mei 2024",
    verified: true
  },
  {
    id: 9,
    name: "Hendra Gunawan",
    profession: "IT Consultant",
    location: "Tangerang, Banten",
    car: "Mazda CX-5 Elite 2020",
    purchasePrice: "Rp 385.000.000",
    marketPrice: "Rp 420.000.000",
    savings: "Rp 35.000.000",
    message: "Sudah 2 kali menang lelang di sini. Pertama Mazda CX-5, kedua Honda Civic. Keduanya kondisi excellent. Yang saya suka, semua mobil sudah di-inspect ketat sama tim teknis mereka. Jadi kita beli dengan tenang. Sistem lelangnya juga seru, adrenalin!",
    image: "/avatar-man-2.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "November 2024",
    verified: true
  },
  {
    id: 10,
    name: "Lina Marlina",
    profession: "Pengusaha Online Shop",
    location: "Depok, Jawa Barat",
    car: "Toyota Rush G AT 2021",
    purchasePrice: "Rp 225.000.000",
    marketPrice: "Rp 245.000.000",
    savings: "Rp 20.000.000",
    message: "Butuh mobil untuk kirim barang online shop. Dapat Rush dengan harga bagus di LelangMobil. Proses KYC cepat, deposit mudah, lelangnya fair. Setelah menang, proses serah terima juga lancar. Mobil sesuai deskripsi, tidak ada yang disembunyikan. Mantap!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/toyota-avanza-2022.svg",
    rating: 5,
    date: "Oktober 2024",
    verified: true
  },
  {
    id: 11,
    name: "Bambang Suryanto",
    profession: "Pegawai Bank",
    location: "Malang, Jawa Timur",
    car: "Nissan Livina VL AT 2020",
    purchasePrice: "Rp 165.000.000",
    marketPrice: "Rp 180.000.000",
    savings: "Rp 15.000.000",
    message: "Sebagai pegawai bank, saya paham betul soal transaksi keuangan. LelangMobil sistemnya aman dan terpercaya. Deposit langsung masuk ke rekening resmi, withdraw juga cepat. Livina yang saya dapat kondisinya bagus, cocok untuk keluarga kecil.",
    image: "/avatar-man-1.svg",
    carImage: "/cars/toyota-avanza-2022.svg",
    rating: 5,
    date: "September 2024",
    verified: true
  },
  {
    id: 12,
    name: "Fitri Handayani",
    profession: "Apoteker",
    location: "Palembang, Sumatera Selatan",
    car: "Honda Mobilio E CVT 2021",
    purchasePrice: "Rp 175.000.000",
    marketPrice: "Rp 190.000.000",
    savings: "Rp 15.000.000",
    message: "Pertama kali ikut lelang online, deg-degan tapi seru! Alhamdulillah menang Mobilio dengan harga bagus. Prosesnya transparan, semua bid tercatat. Customer service responsif banget, chat langsung dibalas. Mobilio-nya mulus, AC dingin, mesin halus. Puas!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/honda-crv-2023.svg",
    rating: 5,
    date: "Agustus 2024",
    verified: true
  },
  {
    id: 13,
    name: "Dedi Kurniawan",
    profession: "Arsitek",
    location: "Bekasi, Jawa Barat",
    car: "Mitsubishi Xpander Ultimate 2022",
    purchasePrice: "Rp 265.000.000",
    marketPrice: "Rp 285.000.000",
    savings: "Rp 20.000.000",
    message: "Xpander Ultimate yang saya cari akhirnya dapat di LelangMobil dengan harga 20 juta lebih murah! Fitur lengkap, panoramic roof, leather seat, semua berfungsi normal. Proses lelang fair, tidak ada kecurangan. Highly recommended untuk yang cari mobil berkualitas!",
    image: "/avatar-man-2.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "Juli 2024",
    verified: true
  },
  {
    id: 14,
    name: "Sari Wulandari",
    profession: "Desainer Grafis",
    location: "Bali",
    car: "Suzuki Baleno Hatchback 2020",
    purchasePrice: "Rp 155.000.000",
    marketPrice: "Rp 170.000.000",
    savings: "Rp 15.000.000",
    message: "Butuh mobil compact untuk keliling Bali. Dapat Baleno di LelangMobil dengan harga oke. Mobilnya irit BBM, nyaman dikendarai, cocok untuk daily use. Proses dari bid sampai terima mobil kurang dari 2 minggu. Efisien banget!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/toyota-avanza-2022.svg",
    rating: 5,
    date: "Juni 2024",
    verified: true
  },
  {
    id: 15,
    name: "Agus Salim",
    profession: "Kontraktor",
    location: "Balikpapan, Kalimantan Timur",
    car: "Toyota Hilux Double Cabin 2019",
    purchasePrice: "Rp 385.000.000",
    marketPrice: "Rp 420.000.000",
    savings: "Rp 35.000.000",
    message: "Butuh pickup untuk proyek. Dapat Hilux di LelangMobil dengan harga jauh lebih murah dari dealer. Kondisi mobil bagus, mesin kuat, cocok untuk medan berat. Tim LelangMobil profesional, proses cepat. Mantap jiwa!",
    image: "/avatar-man-1.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "Mei 2024",
    verified: true
  },
  {
    id: 16,
    name: "Maya Kusuma",
    profession: "Psikolog",
    location: "Yogyakarta",
    car: "Mazda 2 R AT 2021",
    purchasePrice: "Rp 215.000.000",
    marketPrice: "Rp 235.000.000",
    savings: "Rp 20.000.000",
    message: "Mazda 2 impian akhirnya terwujud lewat LelangMobil! Harga lebih murah 20 juta dari showroom. Mobilnya masih wangi baru, kilometer baru 15rb. Fitur safety lengkap. Proses lelang seru, customer service ramah. Terima kasih LelangMobil!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/honda-crv-2023.svg",
    rating: 5,
    date: "April 2024",
    verified: true
  },
  {
    id: 17,
    name: "Rudi Hartono",
    profession: "Sales Manager",
    location: "Surabaya, Jawa Timur",
    car: "BMW 320i Sport 2018",
    purchasePrice: "Rp 485.000.000",
    marketPrice: "Rp 530.000.000",
    savings: "Rp 45.000.000",
    message: "Selalu pengen punya BMW. Lewat LelangMobil akhirnya kesampaian dengan budget yang masuk akal. BMW 320i yang saya dapat kondisinya istimewa, service record lengkap di BMW Astra. Proses lelang profesional, tidak ada drama. Recommended!",
    image: "/avatar-man-2.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "Maret 2024",
    verified: true
  },
  {
    id: 18,
    name: "Nia Ramadhani",
    profession: "Influencer",
    location: "Jakarta Selatan",
    car: "Mercedes-Benz C200 2019",
    purchasePrice: "Rp 585.000.000",
    marketPrice: "Rp 640.000.000",
    savings: "Rp 55.000.000",
    message: "Butuh mobil mewah untuk konten. Dapat Mercedes C200 di LelangMobil dengan harga 55 juta lebih murah! Mobilnya perfect, interior mewah, teknologi canggih. Proses lelang smooth, tim profesional. Followers juga banyak yang tanya, saya rekomendasikan LelangMobil!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "Februari 2024",
    verified: true
  },
  {
    id: 19,
    name: "Fajar Ramadhan",
    profession: "Fotografer",
    location: "Bandung, Jawa Barat",
    car: "Suzuki Jimny 2021",
    purchasePrice: "Rp 385.000.000",
    marketPrice: "Rp 410.000.000",
    savings: "Rp 25.000.000",
    message: "Jimny untuk hunting foto landscape akhirnya dapat! Lewat LelangMobil hemat 25 juta. Mobilnya keren, 4x4 berfungsi sempurna, cocok untuk off-road. Proses lelang fair, tidak ada bot atau kecurangan. Puas banget!",
    image: "/avatar-man-1.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "Januari 2024",
    verified: true
  },
  {
    id: 20,
    name: "Dian Sastro",
    profession: "Event Organizer",
    location: "Jakarta Pusat",
    car: "Toyota Alphard G 2018",
    purchasePrice: "Rp 685.000.000",
    marketPrice: "Rp 750.000.000",
    savings: "Rp 65.000.000",
    message: "Butuh Alphard untuk client VIP. Dapat di LelangMobil dengan harga 65 juta lebih murah dari pasaran! Kondisi mobil excellent, interior mewah, captain seat nyaman. Tim LelangMobil sangat membantu proses serah terima. Highly recommended untuk yang cari mobil premium!",
    image: "/avatar-woman-1.svg",
    carImage: "/cars/mitsubishi-pajero-2021.svg",
    rating: 5,
    date: "Desember 2023",
    verified: true
  }
]

// Enhanced bank list with official partnership details with official partnership details
export const bankList = [
  { 
    code: "BCA", 
    name: "Bank Central Asia", 
    accountNumber: "1234567890", 
    accountName: "PT LelangMobil Indonesia",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Bank_Central_Asia.svg/200px-Bank_Central_Asia.svg.png",
    features: ["Transfer Real-time", "Mobile Banking", "Internet Banking"],
    partnerSince: "2020",
    isPreferred: true
  },
  { 
    code: "MANDIRI", 
    name: "Bank Mandiri", 
    accountNumber: "0987654321", 
    accountName: "PT LelangMobil Indonesia",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/Bank_Mandiri_logo_2016.svg/200px-Bank_Mandiri_logo_2016.svg.png",
    features: ["Livin' by Mandiri", "ATM Terluas", "Transfer Instan"],
    partnerSince: "2020",
    isPreferred: true
  },
  { 
    code: "BRI", 
    name: "Bank Rakyat Indonesia", 
    accountNumber: "1122334455", 
    accountName: "PT LelangMobil Indonesia",
    logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/BRI_2020.svg/200px-BRI_2020.svg.png",
    features: ["BRImo", "Jaringan Terluas", "Transfer 24/7"],
    partnerSince: "2021",
    isPreferred: true
  },
  { 
    code: "BNI", 
    name: "Bank Negara Indonesia", 
    accountNumber: "5544332211", 
    accountName: "PT LelangMobil Indonesia",
    logo: "https://upload.wikimedia.org/wikipedia/id/thumb/5/55/BNI_logo.svg/200px-BNI_logo.svg.png",
    features: ["BNI Mobile", "Taplus", "Transfer Cepat"],
    partnerSince: "2021",
    isPreferred: false
  },
  { 
    code: "CIMB", 
    name: "Bank CIMB Niaga", 
    accountNumber: "7788990011", 
    accountName: "PT LelangMobil Indonesia",
    logo: "/banks/cimb-logo.png",
    features: ["OCTO Mobile", "Go Mobile", "Transfer Mudah"],
    partnerSince: "2022",
    isPreferred: false
  },
  { 
    code: "DANAMON", 
    name: "Bank Danamon", 
    accountNumber: "2233445566", 
    accountName: "PT LelangMobil Indonesia",
    logo: "/banks/danamon-logo.png",
    features: ["D-Bank Pro", "Hello Danamon", "Transfer Aman"],
    partnerSince: "2022",
    isPreferred: false
  }
]

// Company partnerships and certifications
export const partnerships = [
  {
    category: "Financial Partners",
    partners: [
      { name: "Bank Central Asia", logo: "/banks/bca-logo.png", type: "Primary Banking Partner" },
      { name: "Bank Mandiri", logo: "/banks/mandiri-logo.png", type: "Strategic Partner" },
      { name: "Bank Rakyat Indonesia", logo: "/banks/bri-logo.png", type: "Regional Partner" },
      { name: "Bank Negara Indonesia", logo: "/banks/bni-logo.png", type: "Government Banking" }
    ]
  },
  {
    category: "Technology Partners",
    partners: [
      { name: "Amazon Web Services", logo: "/partners/aws-logo.png", type: "Cloud Infrastructure" },
      { name: "Cloudflare", logo: "/partners/cloudflare-logo.png", type: "Security & CDN" },
      { name: "Stripe", logo: "/partners/stripe-logo.png", type: "Payment Processing" }
    ]
  },
  {
    category: "Security Certifications",
    partners: [
      { name: "ISO 27001", logo: "/security/iso-27001.png", type: "Information Security" },
      { name: "SSL Certificate", logo: "/security/ssl-secured.png", type: "Data Encryption" },
      { name: "PCI DSS", logo: "/security/pci-dss.png", type: "Payment Security" },
      { name: "Kominfo Certified", logo: "/security/kominfo-certified.png", type: "Government Compliance" }
    ]
  }
]
